import "../styles/globals.css";
import Header from "./components/Header";
import Providers from "./components/Providers";

export const metadata = {
  title: "Karge's News",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700">
          <Providers>
            <Header />
            <div className="max-w-6xl mx-auto">{children}</div>
          </Providers>
        </div>
      </body>
    </html>
  );
}
