import { Suspense } from "react";
import "../styles/globals.css";
import Header from "./components/Header";
import Providers from "./components/Providers";
import Loading from "./search/loading";

export const metadata = {
  title: "Karge's News",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <div className="bg-gray-100 dark:bg-zinc-900 transition-all duration-700">
          <Providers>
            <Header />
            <Suspense fallback={<Loading />}>
              <div className="max-w-6xl mx-auto">{children}</div>
            </Suspense>
          </Providers>
        </div>
      </body>
    </html>
  );
}
